name: GitHub Metrics
on:
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: daspranay918
          template: classic
          base: header, activity, community, repositories, metadata

          config_timezone: Asia/Kolkata

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full

          plugin_followup: yes

          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 12
          plugin_languages_colors: github
          plugin_languages_sections: most-used

          plugin_habits: yes
          plugin_habits_charts: yes

          plugin_calendar: yes
          plugin_calendar_graph: yes
          plugin_calendar_graph_type: three-dimensional

          plugin_pagespeed: yes
          plugin_pagespeed_token: ${{ secrets.METRICS_TOKEN }}
          plugin_pagespeed_url: https://github.com

          plugin_music: yes
          plugin_music_provider: spotify
          plugin_music_mode: playlist
          plugin_music_playlist: "37i9dQZF1DX6VdMW310YC7"
